---
- hosts: new-servers
  tasks:
   - name: Remove password requirement for deploy sudo temporarily
     lineinfile: 'dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) NOPASSWD: ALL" state=present'

   - name: Copy built files to /var/www/kodemaker.no
     synchronize: src=../build/ dest=/var/www/kodemaker.no/ owner=yes group=yes rsync_path="sudo rsync" delete=yes

   - name: Require password for sudo again
     lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

   - name: Purge all html files from varnish
     command: varnishadm -S /etc/varnish/secret -T localhost:6082 "purge req.url ~ (/|[.]html)$"
