---
- hosts: new-servers
  tasks:
   - name: Install nginx
     yum: name=nginx state=present

   - name: Create kodemaker.no directory
     file: state=directory path=/var/www/kodemaker.no/ owner=nginx group=nginx

   - name: Configure nginx
     template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
     notify:
      - restart nginx

   - name: Create sites-enabled/available directories
     file: state=directory path=/etc/nginx/{{ item }} owner=nginx group=nginx
     with_items:
      - sites-enabled
      - sites-available

   - name: Write sites-available/kodemaker.no
     template: src=templates/sites-available/kodemaker.no.j2 dest=/etc/nginx/sites-available/kodemaker.no
     notify:
      - restart nginx

   - name: Symlink kodemaker.no into sites-enabled
     file: src=/etc/nginx/sites-available/kodemaker.no
           dest=/etc/nginx/sites-enabled/kodemaker.no
           owner=nginx
           group=nginx
           state=link

   - name: Install varnish
     yum: name=varnish state=present

   - name: Configure varnish sysconfig
     template: src=templates/varnish.j2 dest=/etc/sysconfig/varnish
     notify:
      - restart varnish

   - name: Configure varnish vcl
     template: src=templates/varnish.vcl.j2 dest=/etc/varnish/default.vcl
     notify:
      - restart varnish

   - name: Check if iptables is operational (it isnt on VPSes)
     stat: path=/etc/sysconfig/iptables
     register: iptables_info

   - name: open port 80 in firewall
     lineinfile: dest=/etc/sysconfig/iptables regexp="-p tcp --dport 80 -j ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" insertafter="-p tcp --dport 22 -j ACCEPT"
     when: iptables_info.stat.exists == true
     notify:
      - restart iptables

   - name: Install rsync
     yum: name=rsync state=present

   - name: No tty required for rsync
     lineinfile: dest=/etc/sudoers regexp="Defaults!/usr/bin/rsync" line="Defaults!/usr/bin/rsync !requiretty"

  handlers:
   - name: restart nginx
     service: name=nginx state=restarted enabled=yes

   - name: restart iptables
     service: name=iptables state=restarted enabled=yes

   - name: restart varnish
     service: name=varnish state=restarted enabled=yes
