---
- hosts: new-servers
  tasks:
   - name: Install nginx
     yum: name=nginx state=present

   - name: Create kodemaker.no directory
     file: state=directory path=/var/www/kodemaker.no/ owner=nginx group=nginx

   - name: Write nginx.conf
     template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
     notify:
      - restart nginx

   - name: Check if iptables is operational (it isnt on VPSes)
     stat: path=/etc/sysconfig/iptables
     register: iptables_info

   - name: open port 80 in firewall
     lineinfile: dest=/etc/sysconfig/iptables regexp="-p tcp --dport 80 -j ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" insertafter="-p tcp --dport 22 -j ACCEPT"
     when: iptables_info.stat.exists == true
     notify:
      - restart iptables

  handlers:
   - name: restart nginx
     service: name=nginx state=restarted enabled=yes

   - name: restart iptables
     service: name=iptables state=restarted enabled=yes